/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import gui.SeleccionPokemonGUI;


public class BarraProgreso extends javax.swing.JFrame {

    /**
     * Creates new form BarraProgreso
     */
    public BarraProgreso() {
        initComponents();
        setTitle("Cargando Juego");
     setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadingBar = new javax.swing.JProgressBar();
        LoadingValue = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 560, 10));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText("0%");
        getContentPane().add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        LoadingLabel.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLabel.setText("Loading");
        getContentPane().add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 170, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonproyecto/img/Diseño_sin_título__2_-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 200, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonproyecto/img/FondoVerde.jpg"))); // NOI18N
        jLabel1.setText("Cargando....");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 560, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void iniciarCarga() {
    new Thread(() -> { // Hilo para evitar que la interfaz se congele
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(65);
                LoadingValue.setText(i + "%");

                // Mensajes de carga
                if (i == 10) LoadingLabel.setText("Cargando el Sistema");
                if (i == 20) LoadingLabel.setText("Cargando Gráficos");
                if (i == 30) LoadingLabel.setText("Cargando los Servidores");
                if (i == 50) LoadingLabel.setText("Creando Combates");
                if (i == 60) LoadingLabel.setText("Corriendo el Programa");
                if (i == 80) LoadingLabel.setText("Actualizando el Sistema");
                if (i == 90) LoadingLabel.setText("Ya casi está listo");

                LoadingBar.setValue(i);
            }

            // Cerrar la barra de progreso y abrir la ventana Pokémon
            dispose();
            new SeleccionPokemonGUI().setVisible(true);

        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }).start(); // Iniciar el hilo
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarraProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarraProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarraProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarraProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarraProgreso().setVisible(true);
            }
        });
     } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
